blank_issues_enabled: false
contact_links:
  - name: ðŸ”— Quick Create new issue
    url: https://issue.element-plus.org/
    about: The issue which is not created via https://issue.element-plus.org/ will be closed immediately.
  - name: ðŸ¤” Questions and Help
    url: https://github.com/element-plus/element-plus/discussions
    about: Ask questions and request help or other discussions.
